### ISSUE TITLE
Provide APK to download

### ISSUE THREAD

**Issue by Mart-Bogdan** [inferrna/hello_world_android_egui#3]
Hello. I have visited your repo, and I would like to try your demo, but I need to build it sonehow. Would be way better if I'd be able to download it and try right away.

**Comment by Mart-Bogdan** [comment]
Why was this closed? I don't see any link to download in readme. Also no github tags with attachment :'(

**Comment by inferrna** [comment]
This demo has no point by itself. Its purpose is to provide an easy to build example. So, it is not about “what” but is about “how to”. If you intended to try Rust on Android, then you're supposed to have minimal experience in Rust and android build tools, so compiling it should be easy for you. Start with this [BUILD_ANDROID](../blob/master/BUILD_ANDROID.md) instruction and report difficulties you met.
